server {
    listen 8000;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/supabase/ {
        proxy_pass ${SUPABASE_URL}/;
        proxy_set_header Content-Type "application/json";
        proxy_set_header apikey "${SUPABASE_KEY}";
        proxy_set_header Authorization "Bearer ${SUPABASE_KEY}";
        proxy_set_header Host fcwuhwedretyomtrbgzb.supabase.co;
        proxy_ssl_server_name on;
    }

    gzip on;
    gzip_types text/plain text/html text/css application/json application/javascript text/xml;
}
